# Generated by Django 5.2.8 on 2025-12-19 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PointOfInterest',
            new_name='Location',
        ),
    ]
